// Platform scaffolder server.
// Endpoints:
//   POST /api/generate  -> copy a template into output/<projectName>
//   POST /api/validate-config -> sanitize pasted/manual portfolio JSON
//   GET  /api/schema    -> return the content.json schema reference
//   POST /api/push      -> init git, create GitHub repo, commit + push
import "dotenv/config";
import express from "express";
import cors from "cors";
import fs from "fs-extra";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { Octokit, RequestError } from "octokit";
import { simpleGit } from "simple-git";
import rateLimit from "express-rate-limit";
import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { PORTFOLIO_SYSTEM_PROMPT } from "./prompts/portfolioGenerator.js";
import portfolioSchema from "./schema/portfolioSchema.js";
import { validatePortfolioConfigWithWarnings } from "./validators/portfolioValidator.js";
import { generateSQL, tableNameForModule } from "./lib/schemaGenerator.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Repo root = my-platform/ (one level above server/)
const ROOT = path.resolve(__dirname, "..");
const TEMPLATES_DIR = path.join(ROOT, "templates");
const OUTPUT_DIR = path.join(ROOT, "output");
const PORTALS_DIR = path.join(ROOT, "portals");

// Skipped during template copy.
const EXCLUDED = new Set(["node_modules", "dist", ".git"]);

// What every generated project should ignore from git.
const DEFAULT_GITIGNORE = `# Auto-generated by platform server
node_modules
dist
.env
.env.local
.DS_Store
*.log
`;

const DEFAULT_ADMIN_EMAIL = "abc@gmail.com";
const DEFAULT_ADMIN_PASSWORD = "123";

const NAME_RE = /^[a-z0-9-_]+$/i;
const TEMPLATE_ALIASES = new Map([
  ["temp1", "portal-admin"],
  ["template1", "portal-admin"],
  ["template 1", "portal-admin"],
  ["temp2", "portal-admin-v2"],
  ["template2", "portal-admin-v2"],
  ["template 2", "portal-admin-v2"],
  ["topbar temp", "crud-modern-new-temp"],
  ["topbar-temp", "crud-modern-new-temp"],
  ["topbar_temp", "crud-modern-new-temp"],
]);
const CRUD_PORTAL_TEMPLATE_IDS = new Set([
  "portal-admin",
  "portal-admin-v2",
  "crud-modern-new-temp",
]);
const PORTAL_ADMIN_RUNTIME_TEMPLATE_IDS = new Set(["portal-admin", "portal-admin-v2"]);
const TOPBAR_TEMPLATE_ID = "crud-modern-new-temp";
const OPTION_FIELD_TYPES = new Set(["select", "radio", "multi-select", "checkbox-group"]);

function normalizeTemplateKey(templateId) {
  return String(templateId || "")
    .trim()
    .toLowerCase()
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ");
}

function resolveTemplateId(templateId) {
  const raw = String(templateId || "").trim();
  const normalized = normalizeTemplateKey(raw);
  return TEMPLATE_ALIASES.get(normalized) || TEMPLATE_ALIASES.get(raw.toLowerCase()) || raw;
}

function isCrudPortalTemplate(templateId) {
  return CRUD_PORTAL_TEMPLATE_IDS.has(templateId);
}

function isPortalConfigTemplate(templateId) {
  return isCrudPortalTemplate(templateId) || String(templateId || "").startsWith("portal");
}

function validateResolvedTemplateId(templateId) {
  const resolvedTemplateId = resolveTemplateId(templateId);
  return NAME_RE.test(resolvedTemplateId) ? resolvedTemplateId : "";
}

const PORTAL_FIELD_TYPES = new Set([
  "text",
  "email",
  "password",
  "phone",
  "url",
  "textarea",
  "number",
  "currency",
  "percentage",
  "rating",
  "select",
  "multi-select",
  "checkbox",
  "checkbox-group",
  "toggle",
  "radio",
  "date",
  "time",
  "datetime",
  "file",
  "image",
  "avatar",
  "tags",
  "color",
  "address",
  "json",
  "reference",
]);

const PORTAL_INDUSTRIES = [
  "healthcare",
  "crm",
  "hrms",
  "school",
  "inventory",
  "erp",
  "generic",
];

const INDUSTRY_DEFAULTS = {
  generic: {
    badge: "Business Operations",
    headline: "Run your operations from one focused workspace",
    highlightText: "operations",
    description: "Manage records, tasks, approvals, and daily workflows from one secure dashboard.",
    footerText: "Powered by your operations team",
  },
  healthcare: {
    badge: "Care Operations",
    headline: "Coordinate care records with clarity",
    highlightText: "care records",
    description: "Track visits, appointments, teams, and operational workflows from one secure portal.",
    footerText: "Secure care operations portal",
  },
  crm: {
    badge: "Customer Management",
    headline: "Manage your customers with ease",
    highlightText: "customers",
    description: "Manage records, workflows, and operations from one place.",
    footerText: "Customer operations workspace",
  },
  hrms: {
    badge: "People Operations",
    headline: "Manage employees, leave, and HR workflows",
    highlightText: "employees",
    description: "Keep employee records, approvals, and HR operations organized in one secure portal.",
    footerText: "People operations portal",
  },
  school: {
    badge: "School Management",
    headline: "Run student and campus operations smoothly",
    highlightText: "student",
    description: "Manage student records, fees, classes, and school workflows from a single dashboard.",
    footerText: "School administration portal",
  },
  inventory: {
    badge: "Inventory Control",
    headline: "Track stock, products, and movement in real time",
    highlightText: "stock",
    description: "Manage inventory records, stock movement, suppliers, and reorder workflows from one place.",
    footerText: "Inventory operations portal",
  },
  erp: {
    badge: "Enterprise Operations",
    headline: "Bring vendors, purchases, and operations together",
    highlightText: "operations",
    description: "Coordinate enterprise records, procurement workflows, and approvals from one system.",
    footerText: "Enterprise operations portal",
  },
};

const THEME_PRESET_COLORS = {
  blue: "#2563eb",
  red: "#dc2626",
  green: "#16a34a",
  purple: "#7c3aed",
  slate: "#334155",
};

function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function safePortalSlug(value) {
  const slug = slugify(value);
  return NAME_RE.test(slug) ? slug : "";
}

function initialsForName(value = "") {
  const words = String(value || "")
    .replace(/[^a-zA-Z0-9 ]/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (!words.length) return "AP";
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return words.slice(0, 2).map((word) => word[0]).join("").toUpperCase();
}

function industryDefaults(industry = "generic") {
  return INDUSTRY_DEFAULTS[industry] || INDUSTRY_DEFAULTS.generic;
}

function normalizeLoginPage(rawLoginPage = {}, { appName, industry, footerText }) {
  const defaults = industryDefaults(industry);
  const features = Array.isArray(rawLoginPage.features)
    ? rawLoginPage.features
        .map((feature) => ({
          title: String(feature?.title || "").trim(),
          description: String(feature?.description || "").trim(),
        }))
        .filter((feature) => feature.title && feature.description)
    : [];

  return {
    portalName: rawLoginPage.portalName || appName,
    badge: rawLoginPage.badge || defaults.badge,
    headline: rawLoginPage.headline || defaults.headline,
    highlightText: rawLoginPage.highlightText || defaults.highlightText,
    description: rawLoginPage.description || defaults.description,
    features: features.length
      ? features
      : [
          {
            title: "Secure Access",
            description: "Enterprise-grade authentication for authorized users.",
          },
          {
            title: "Self Service",
            description: "Manage records, workflows, and operations from one dashboard.",
          },
        ],
    footerText: rawLoginPage.footerText || footerText || defaults.footerText,
  };
}

function hexToRgb(hex) {
  const normalized = String(hex || "").replace("#", "");
  if (!/^[0-9a-f]{6}$/i.test(normalized)) return { r: 37, g: 99, b: 235 };
  return {
    r: Number.parseInt(normalized.slice(0, 2), 16),
    g: Number.parseInt(normalized.slice(2, 4), 16),
    b: Number.parseInt(normalized.slice(4, 6), 16),
  };
}

function rgbToHex({ r, g, b }) {
  return `#${[r, g, b]
    .map((component) => Math.max(0, Math.min(255, Math.round(component))).toString(16).padStart(2, "0"))
    .join("")}`;
}

function mixHex(hex, mixWith, weight = 0.5) {
  const a = hexToRgb(hex);
  const b = hexToRgb(mixWith);
  return rgbToHex({
    r: a.r * (1 - weight) + b.r * weight,
    g: a.g * (1 - weight) + b.g * weight,
    b: a.b * (1 - weight) + b.b * weight,
  });
}

function hexToHsl(hex) {
  const { r, g, b } = hexToRgb(hex);
  const red = r / 255;
  const green = g / 255;
  const blue = b / 255;
  const max = Math.max(red, green, blue);
  const min = Math.min(red, green, blue);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const delta = max - min;
    s = l > 0.5 ? delta / (2 - max - min) : delta / (max + min);
    switch (max) {
      case red:
        h = (green - blue) / delta + (green < blue ? 6 : 0);
        break;
      case green:
        h = (blue - red) / delta + 2;
        break;
      default:
        h = (red - green) / delta + 4;
        break;
    }
    h /= 6;
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

function themeTokensFromColor(hex) {
  const { r, g, b } = hexToRgb(hex);
  const primaryHover = mixHex(hex, "#000000", 0.18);
  const primaryLight = mixHex(hex, "#ffffff", 0.88);
  const accent = mixHex(hex, "#ffffff", 0.12);
  const accent2 = mixHex(hex, "#ffffff", 0.68);
  const { r: ar, g: ag, b: ab } = hexToRgb(accent);
  const { r: a2r, g: a2g, b: a2b } = hexToRgb(accent2);
  return {
    primary: hexToHsl(hex),
    "primary-hover": hexToHsl(primaryHover),
    "primary-light": hexToHsl(primaryLight),
    ring: hexToHsl(hex),
    "sidebar-ring": hexToHsl(hex),
    "auth-panel-orb": hexToHsl(hex),
    "brand-primary": hex,
    "brand-primary-hover": primaryHover,
    "brand-primary-light": primaryLight,
    "brand-primary-rgb": `${r}, ${g}, ${b}`,
    "brand-accent": accent,
    "brand-accent-2": accent2,
    "brand-accent-rgb": `${ar}, ${ag}, ${ab}`,
    "brand-accent-2-rgb": `${a2r}, ${a2g}, ${a2b}`,
    "gradient-start": hex,
    "gradient-end": primaryHover,
    "chart-primary": hex,
    "chart-secondary": accent,
    "chart-tertiary": accent2,
  };
}

function escapeSqlLiteral(value) {
  return String(value || "").replaceAll("'", "''");
}

function nowIso() {
  return new Date().toISOString();
}

function portalConfigPath(slug) {
  return path.join(PORTALS_DIR, slug, "config.json");
}

function portalDataPath(slug, entity) {
  return path.join(PORTALS_DIR, slug, "data", `${entity}.json`);
}

const portalFieldSchema = z
  .object({
    id: z.string().optional(),
    key: z.string().regex(/^[a-zA-Z][a-zA-Z0-9_]*$/),
    label: z.string().min(1),
    type: z.string().min(1),
    required: z.boolean().default(false),
    width: z.enum(["full", "half", "third"]).default("full"),
    placeholder: z.string().optional().default(""),
    helpText: z.string().optional().default(""),
    options: z.array(z.string()).optional().default([]),
    settings: z.record(z.any()).optional().default({}),
    features: z
      .object({
        filter: z.boolean().optional().default(false),
      })
      .passthrough()
      .optional()
      .default({ filter: false }),
  })
  .passthrough();

const portalModuleSchema = z
  .object({
    id: z.string().regex(/^[a-z0-9-]+$/),
    singularName: z.string().min(1),
    pluralName: z.string().min(1),
    icon: z.string().optional().default("Database"),
    fields: z.array(portalFieldSchema).min(1),
    listColumns: z.array(z.string()).optional().default([]),
    tableFeatures: z
      .object({
        sort: z.boolean().optional().default(true),
        filter: z.boolean().optional().default(true),
        search: z.boolean().optional().default(true),
        pagination: z.boolean().optional().default(true),
        export: z.boolean().optional().default(false),
      })
      .optional()
      .default({
        sort: true,
        filter: true,
        search: true,
        pagination: true,
        export: false,
      }),
  })
  .passthrough();

const portalLoginPageSchema = z
  .object({
    portalName: z.string().optional().default(""),
    badge: z.string().optional().default(""),
    headline: z.string().optional().default(""),
    highlightText: z.string().optional().default(""),
    description: z.string().optional().default(""),
    features: z
      .array(
        z.object({
          title: z.string().default(""),
          description: z.string().default(""),
        })
      )
      .optional()
      .default([]),
    footerText: z.string().optional().default(""),
  })
  .passthrough()
  .optional()
  .default({});

const portalConfigSchema = z
  .object({
    version: z.number().optional().default(1),
    templateId: z.string().optional().default("portal-admin"),
    slug: z.string().min(1),
    portalName: z.string().min(1),
    appName: z.string().min(1),
    type: z.enum(["admin", "insurance", "management", "custom"]).default("admin"),
    industry: z.enum(PORTAL_INDUSTRIES).optional().default("generic"),
    themePreset: z.string().optional().default("custom"),
    themeColor: z
      .string()
      .regex(/^#[0-9a-f]{6}$/i)
      .default("#1e40af"),
    logoUrl: z.string().optional().default(""),
    logoText: z.string().optional().default(""),
    loginPage: portalLoginPageSchema,
    footer: z
      .object({
        text: z.string().optional().default(""),
      })
      .passthrough()
      .optional()
      .default({}),
    company: z
      .object({
        name: z.string().optional().default(""),
        website: z.string().optional().default(""),
        supportEmail: z.string().optional().default(""),
        address: z.string().optional().default(""),
      })
      .passthrough()
      .optional()
      .default({}),
    auth: z
      .object({
        screens: z
          .object({
            login: z.boolean().optional().default(true),
            signup: z.boolean().optional().default(true),
            forgotPassword: z.boolean().optional().default(false),
          })
          .optional()
          .default({ login: true, signup: true, forgotPassword: false }),
        method: z.enum(["email-password", "magic-link"]).default("email-password"),
      })
      .optional()
      .default({
        screens: { login: true, signup: true, forgotPassword: false },
        method: "email-password",
      }),
    dashboard: z
      .object({
        enabled: z.boolean().optional().default(true),
        template: z
          .enum(["stats-overview", "charts", "minimal"])
          .optional()
          .default("stats-overview"),
      })
      .optional()
      .default({ enabled: true, template: "stats-overview" }),
    profile: z
      .object({
        enabled: z.boolean().optional().default(true),
      })
      .optional()
      .default({ enabled: true }),
    modules: z.array(portalModuleSchema).min(1),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
  })
  .passthrough();

function normalizePortalConfig(rawConfig) {
  const rawSlug = safePortalSlug(rawConfig?.slug || rawConfig?.portalName || rawConfig?.appName);
  if (!rawSlug) {
    throw new Error("Portal slug is invalid.");
  }
  const appName = String(rawConfig?.appName || rawConfig?.portalName || rawSlug);
  const industry = PORTAL_INDUSTRIES.includes(rawConfig?.industry)
    ? rawConfig.industry
    : "generic";
  const requestedThemePreset = String(
    rawConfig?.themePreset ||
      (typeof rawConfig?.theme === "string" ? rawConfig.theme : "") ||
      "custom"
  ).toLowerCase();
  const themeColor =
    rawConfig?.themeColor ||
    THEME_PRESET_COLORS[requestedThemePreset] ||
    THEME_PRESET_COLORS.blue;
  const footerText =
    rawConfig?.footer?.text ||
    rawConfig?.loginPage?.footerText ||
    industryDefaults(industry).footerText;
  const loginPage = normalizeLoginPage(rawConfig?.loginPage || {}, {
    appName,
    industry,
    footerText,
  });

  const modules = (rawConfig.modules || []).map((module) => {
    const id = safePortalSlug(module.id || module.pluralName || module.singularName);
    const fields = (module.fields || []).map((field) => {
      const key = String(
        field.key ||
          slugify(field.label || field.id)
            .replace(/-/g, "_")
      );
      return {
        ...field,
        id: field.id || crypto.randomUUID(),
        key,
        type: PORTAL_FIELD_TYPES.has(field.type) ? field.type : "text",
        features: {
          filter: !!field.features?.filter,
          ...(field.features || {}),
        },
      };
    });
    const listColumns = (module.listColumns || []).filter((key) =>
      fields.some((field) => field.key === key)
    );
    return {
      ...module,
      id,
      fields,
      listColumns: listColumns.length
        ? listColumns
        : fields.slice(0, 5).map((field) => field.key),
    };
  });

  const parsed = portalConfigSchema.parse({
    ...rawConfig,
    slug: rawSlug,
    appName,
    industry,
    themePreset: requestedThemePreset,
    themeColor,
    logoText: rawConfig?.logoText || initialsForName(appName),
    footer: {
      ...(rawConfig?.footer || {}),
      text: footerText,
    },
    company: {
      name: rawConfig?.company?.name || appName,
      website: rawConfig?.company?.website || "",
      supportEmail: rawConfig?.company?.supportEmail || "",
      address: rawConfig?.company?.address || "",
      ...(rawConfig?.company || {}),
    },
    loginPage,
    modules,
    createdAt: rawConfig.createdAt || nowIso(),
    updatedAt: nowIso(),
  });

  const moduleIds = new Set();
  for (const module of parsed.modules) {
    if (moduleIds.has(module.id)) {
      throw new Error(`Duplicate module id "${module.id}".`);
    }
    moduleIds.add(module.id);
    const fieldKeys = new Set();
    for (const field of module.fields) {
      if (fieldKeys.has(field.key)) {
        throw new Error(`Duplicate field key "${field.key}" in ${module.pluralName}.`);
      }
      fieldKeys.add(field.key);
    }
  }

  return parsed;
}

function numberSetting(value) {
  if (value === "" || value === undefined || value === null) return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function optionalRecordValue(schema) {
  return z.preprocess(
    (value) => (value === "" ? undefined : value),
    schema.optional().nullable()
  );
}

function schemaForPortalField(field) {
  const settings = field.settings || {};
  let schema;

  switch (field.type) {
    case "email":
      schema = z.string().email(`${field.label} must be a valid email.`);
      break;
    case "number":
    case "currency": {
      schema = z.coerce.number();
      const min = numberSetting(settings.min);
      const max = numberSetting(settings.max);
      if (min !== undefined) schema = schema.min(min);
      if (max !== undefined) schema = schema.max(max);
      break;
    }
    case "select":
    case "radio": {
      const options = (field.options || []).filter(Boolean);
      schema = z.string();
      if (options.length) {
        schema = schema.refine((value) => options.includes(value), {
          message: `${field.label} must match a configured option.`,
        });
      }
      break;
    }
    case "multi-select":
    case "tags":
      schema = z.preprocess((value) => {
        if (Array.isArray(value)) return value;
        if (typeof value === "string") {
          return value
            .split(",")
            .map((item) => item.trim())
            .filter(Boolean);
        }
        return [];
      }, z.array(z.string()));
      break;
    case "checkbox":
    case "toggle":
      schema = z.boolean();
      break;
    case "date":
    case "file":
    case "image":
    case "password":
    case "textarea":
    case "text":
    default: {
      schema = z.string();
      const minLength = numberSetting(settings.minLength);
      const maxLength = numberSetting(settings.maxLength);
      if (minLength !== undefined) schema = schema.min(minLength);
      if (maxLength !== undefined) schema = schema.max(maxLength);
      break;
    }
  }

  if (field.required) {
    if (field.type === "multi-select" || field.type === "tags") {
      return schema.refine((value) => value.length > 0, {
        message: `${field.label} is required.`,
      });
    }
    if (field.type === "checkbox" || field.type === "toggle") {
      return schema;
    }
    return schema.refine((value) => value !== undefined && value !== "", {
      message: `${field.label} is required.`,
    });
  }

  return optionalRecordValue(schema);
}

function buildRecordSchema(module) {
  const shape = {};
  for (const field of module.fields || []) {
    shape[field.key] = schemaForPortalField(field);
  }
  return z.object(shape).strip();
}

async function readPortalConfig(slug) {
  const safeSlug = safePortalSlug(slug);
  if (!safeSlug || safeSlug !== slug) {
    const err = new Error("Invalid portal slug.");
    err.status = 400;
    throw err;
  }
  const configPath = portalConfigPath(safeSlug);
  if (!(await fs.pathExists(configPath))) {
    const err = new Error(`Portal "${safeSlug}" not found.`);
    err.status = 404;
    throw err;
  }
  return fs.readJson(configPath);
}

function getModule(config, entity) {
  const safeEntity = safePortalSlug(entity);
  return (config.modules || []).find((module) => module.id === safeEntity);
}

async function readEntityRecords(slug, entity) {
  const dataPath = portalDataPath(slug, entity);
  if (!(await fs.pathExists(dataPath))) return [];
  const data = await fs.readJson(dataPath);
  return Array.isArray(data) ? data : [];
}

async function writeEntityRecords(slug, entity, records) {
  await fs.outputJson(portalDataPath(slug, entity), records, { spaces: 2 });
}

const app = express();
// Restrict CORS to the deployed frontend in production. Set FRONTEND_ORIGIN to your
// Vercel URL (comma-separate multiple origins). If unset, allow all (dev convenience).
const allowedOrigins = (process.env.FRONTEND_ORIGIN || "")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);
app.use(
  cors(
    allowedOrigins.length
      ? {
          origin(origin, callback) {
            // allow same-origin / curl / server-to-server (no Origin header)
            if (!origin || allowedOrigins.includes(origin)) return callback(null, true);
            return callback(new Error(`Origin ${origin} not allowed by CORS`));
          },
        }
      : undefined
  )
);
app.use(express.json({ limit: "2mb" }));

// ---------------------------------------------------------------------------
// GET /api/schema
// ---------------------------------------------------------------------------
app.get("/api/schema", (req, res) => {
  return res.json({ success: true, schema: portfolioSchema });
});

// ---------------------------------------------------------------------------
// POST /api/generate
// ---------------------------------------------------------------------------
app.post("/api/generate", async (req, res) => {
  const { templateId, projectName, config } = req.body || {};
  const resolvedTemplateId = validateResolvedTemplateId(templateId);
  console.log("\n[generate] request:", {
    templateId,
    resolvedTemplateId,
    projectName,
    hasConfig: !!config,
  });

  if (!templateId || !projectName) {
    return res.status(400).json({ success: false, error: "templateId and projectName are required" });
  }
  if (!NAME_RE.test(projectName) || !resolvedTemplateId) {
    return res.status(400).json({
      success: false,
      error: "templateId and projectName must be alphanumeric, dash, or underscore only",
    });
  }

  const srcDir = path.join(TEMPLATES_DIR, resolvedTemplateId);
  const destDir = path.join(OUTPUT_DIR, projectName);

  try {
    console.log("[generate] validating template at:", srcDir);
    if (!(await fs.pathExists(srcDir))) {
      return res.status(404).json({ success: false, error: `Template "${templateId}" not found in templates/` });
    }

    if (await fs.pathExists(destDir)) {
      return res.status(409).json({ success: false, error: `Output "${projectName}" already exists. Pick a different name.` });
    }

    await fs.ensureDir(OUTPUT_DIR);

    console.log("[generate] copying template ->", destDir);
    await fs.copy(srcDir, destDir, {
      filter: (src) => {
        const base = path.basename(src);
        if (EXCLUDED.has(base)) {
          console.log("[generate]   skip:", path.relative(srcDir, src) || base);
          return false;
        }
        return true;
      },
    });

    // KEY CHANGE: when a config is provided, write it directly into the copied
    // template — the config BECOMES the single swappable file that template
    // renders from. Which file depends on the template family:
    //   - landing*  -> src/content.json      (validated portfolio content)
    //   - portal*   -> src/portal-config.json (config-driven admin portal)
    // If no config is provided, the template's bundled default file is kept.
    let generateWarnings = [];
    const isPortal = isPortalConfigTemplate(resolvedTemplateId);

    if (config && typeof config === "object") {
      if (isPortal) {
        // Portal config is written as-is (the template normalises it at runtime
        // via src/config.js). No portfolio validation applies here.
        let configToWrite = config;
        if (isCrudPortalTemplate(resolvedTemplateId)) {
          const normalizedConfig = normalizePortalConfig({
            ...config,
            templateId: resolvedTemplateId,
          });
          normalizedConfig.modules = normalizedConfig.modules.map((module) => ({
            ...module,
            tableName: tableNameForModule(module),
          }));
          configToWrite = resolvedTemplateId === TOPBAR_TEMPLATE_ID
            ? buildTopbarRuntimeConfig(normalizedConfig)
            : await buildPortalAdminRuntimeConfig(normalizedConfig);
        }
        const portalConfigPath = path.join(destDir, "src", "portal-config.json");
        console.log(
          "[generate] Writing portal-config.json, appName:",
          configToWrite?.appName || configToWrite?.branding?.appName,
          "generatedModules:",
          Array.isArray(configToWrite?.generatedModules) ? configToWrite.generatedModules.length : 0
        );
        await fs.writeFile(portalConfigPath, JSON.stringify(configToWrite, null, 2));
        if (isCrudPortalTemplate(resolvedTemplateId)) {
          await writeCrudPortalSupabaseArtifacts(destDir, configToWrite);
        }
      } else {
        // Landing templates: validate + write content.json (existing behaviour).
        const contentPath = path.join(destDir, "src", "content.json");
        const { config: validatedConfig, warnings } = validatePortfolioConfigWithWarnings(config);
        generateWarnings = warnings;
        console.log(
          "[generate] Writing content.json, siteName:",
          validatedConfig.siteName,
          "firstName:",
          validatedConfig.profile?.firstName
        );
        await fs.writeFile(contentPath, JSON.stringify(validatedConfig, null, 2));
      }
    } else {
      console.log(
        `[generate] no config -> keeping template default ${
          isPortal ? "portal-config.json" : "content.json"
        }`
      );
    }

    console.log("[generate] done:", destDir);
    return res.json({
      success: true,
      projectName,
      path: destDir,
      warnings: generateWarnings,
      templateId: resolvedTemplateId,
      requestedTemplateId: templateId,
      message: `Project "${projectName}" generated from template "${resolvedTemplateId}".`,
    });
  } catch (err) {
    console.error("[generate] error:", err);
    return res.status(500).json({ success: false, error: err.message || "Unknown server error" });
  }
});

// ---------------------------------------------------------------------------
// POST /api/generate-config
// Body: { description: string, templateId: string }
// Turn a free-text description into validated content.json via Gemini.
//   - rate limited: 10 req / IP / hour
//   - cached: same description within 1h returns the cached config
//   - one retry if the model returns non-JSON
// ---------------------------------------------------------------------------

// In-memory cache: sha256(description) -> { config, expires }. Cleared on restart.
const CONFIG_CACHE = new Map();
const CACHE_TTL_MS = 60 * 60 * 1000; // 1 hour

function cacheKey(description) {
  return crypto.createHash("sha256").update(description).digest("hex");
}

// ---------------------------------------------------------------------------
// POST /api/validate-config
// Body: { config: object }
// Sanitizes pasted/manual content.json through the same portfolio validator.
// ---------------------------------------------------------------------------
app.post("/api/validate-config", (req, res) => {
  const { config } = req.body || {};
  console.log("\n[validate-config] request:", {
    hasConfig: !!config,
    type: Array.isArray(config) ? "array" : typeof config,
  });

  if (!config || typeof config !== "object" || Array.isArray(config)) {
    return res.status(400).json({
      success: false,
      error: "config object is required",
    });
  }

  const { config: validatedConfig, warnings } = validatePortfolioConfigWithWarnings(config);
  return res.json({ success: true, config: validatedConfig, warnings });
});

// 10 requests per IP per hour.
const generateConfigLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 10,
  standardHeaders: true,
  legacyHeaders: false,
  message: { success: false, error: "Rate limit exceeded: 10 requests per hour. Try again later." },
});

// Call Gemini once and return the parsed JSON object (throws on parse failure).
async function callGemini(ai, description, { retry = false } = {}) {
  const userText = retry
    ? `Your previous output was not valid JSON. Output ONLY valid JSON.\n\nDescription:\n${description}`
    : description;

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: userText,
    config: {
      systemInstruction: PORTFOLIO_SYSTEM_PROMPT,
      responseMimeType: "application/json",
    },
  });

  const text = response.text ?? "";
  return JSON.parse(text); // may throw -> caller decides retry vs 500
}

app.post("/api/generate-config", generateConfigLimiter, async (req, res) => {
  const { description, templateId } = req.body || {};
  const resolvedTemplateId = validateResolvedTemplateId(templateId);
  console.log("\n[generate-config] request received:", {
    templateId,
    resolvedTemplateId,
    descriptionLength: typeof description === "string" ? description.length : 0,
  });

  // --- Input validation ---
  if (!description || typeof description !== "string" || !description.trim()) {
    return res.status(400).json({ success: false, error: "description (non-empty string) is required" });
  }
  if (!templateId || !resolvedTemplateId) {
    return res.status(400).json({ success: false, error: "templateId missing or invalid" });
  }

  // --- API key check ---
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error("[generate-config] GEMINI_API_KEY missing from environment");
    return res.status(500).json({
      success: false,
      error: "Server missing GEMINI_API_KEY. Set it in server/.env. See .env.example.",
    });
  }

  // --- Cache check ---
  const key = cacheKey(description.trim());
  const cached = CONFIG_CACHE.get(key);
  if (cached && cached.expires > Date.now()) {
    console.log("[generate-config] cache HIT ->", key.slice(0, 12));
    return res.json({
      success: true,
      config: cached.config,
      warnings: cached.warnings || [],
      cached: true,
    });
  }
  if (cached) CONFIG_CACHE.delete(key); // expired
  console.log("[generate-config] cache MISS ->", key.slice(0, 12));

  try {
    const ai = new GoogleGenAI({ apiKey });

    // --- AI call (+ one retry on bad JSON) ---
    let parsed;
    try {
      console.log("[generate-config] AI call: gemini-2.5-flash");
      parsed = await callGemini(ai, description.trim());
      console.log("[generate-config] parse: OK");
    } catch (parseErr) {
      console.warn("[generate-config] parse failed, retrying once:", parseErr.message);
      try {
        parsed = await callGemini(ai, description.trim(), { retry: true });
        console.log("[generate-config] parse: OK (after retry)");
      } catch (retryErr) {
        console.error("[generate-config] retry parse failed:", retryErr.message);
        return res.status(500).json({
          success: false,
          error: "AI did not return valid JSON after retry. Try rephrasing the description.",
        });
      }
    }

    // --- Validate / sanitize ---
    console.log("[generate-config] validate: cleaning config");
    const { config: validatedConfig, warnings } = validatePortfolioConfigWithWarnings(parsed);

    // --- Cache + respond ---
    CONFIG_CACHE.set(key, { config: validatedConfig, warnings, expires: Date.now() + CACHE_TTL_MS });
    console.log("[generate-config] respond: success");
    return res.json({ success: true, config: validatedConfig, warnings });
  } catch (err) {
    console.error("[generate-config] error:", err);
    return res.status(500).json({ success: false, error: err.message || "Unknown error generating config" });
  }
});

// ---------------------------------------------------------------------------
// Portal builder storage + JSON-backed CRUD
// ---------------------------------------------------------------------------
app.post("/api/portal/create", async (req, res) => {
  try {
    const config = normalizePortalConfig(req.body || {});
    const portalDir = path.join(PORTALS_DIR, config.slug);
    const configPath = portalConfigPath(config.slug);

    if (await fs.pathExists(configPath)) {
      return res.status(409).json({
        success: false,
        error: `Portal "${config.slug}" already exists. Choose a different slug.`,
      });
    }

    await fs.ensureDir(path.join(portalDir, "data"));
    await fs.outputJson(configPath, config, { spaces: 2 });
    for (const module of config.modules) {
      await fs.outputJson(portalDataPath(config.slug, module.id), [], { spaces: 2 });
    }

    return res.json({
      success: true,
      slug: config.slug,
      portalUrl: `/portal/${config.slug}`,
      shortPortalUrl: `/p/${config.slug}`,
    });
  } catch (err) {
    const issues = err?.issues?.map((issue) => issue.message).join("; ");
    return res.status(400).json({
      success: false,
      error: issues || err.message || "Invalid portal config.",
    });
  }
});

app.get("/api/portal/:slug/config", async (req, res) => {
  try {
    const config = await readPortalConfig(req.params.slug);
    return res.json({ success: true, config });
  } catch (err) {
    return res.status(err.status || 500).json({
      success: false,
      error: err.message || "Could not read portal config.",
    });
  }
});

app.get("/api/portals", async (req, res) => {
  try {
    await fs.ensureDir(PORTALS_DIR);
    const entries = await fs.readdir(PORTALS_DIR);
    const portals = [];
    for (const entry of entries) {
      const configPath = portalConfigPath(entry);
      if (!(await fs.pathExists(configPath))) continue;
      const config = await fs.readJson(configPath);
      portals.push({
        slug: config.slug,
        appName: config.appName,
        type: config.type,
        createdAt: config.createdAt,
      });
    }
    portals.sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)));
    return res.json({ success: true, portals });
  } catch (err) {
    return res.status(500).json({
      success: false,
      error: err.message || "Could not list portals.",
    });
  }
});

app.get("/api/portal/:slug/:entity", async (req, res) => {
  try {
    const config = await readPortalConfig(req.params.slug);
    const module = getModule(config, req.params.entity);
    if (!module) {
      return res.status(404).json({
        success: false,
        error: `Entity "${req.params.entity}" not found in portal config.`,
      });
    }

    let rows = await readEntityRecords(config.slug, module.id);
    const search = String(req.query.search || "").trim().toLowerCase();
    const filterFields = module.fields.filter((field) => field.features?.filter);
    if (search && module.tableFeatures?.filter && filterFields.length) {
      rows = rows.filter((record) =>
        filterFields.some((field) =>
          String(record[field.key] ?? "")
            .toLowerCase()
            .includes(search)
        )
      );
    }

    const sortKey = String(req.query.sort || "");
    if (sortKey && module.tableFeatures?.sort) {
      const dir = String(req.query.dir || "asc") === "desc" ? -1 : 1;
      rows = [...rows].sort((a, b) => {
        const av = a[sortKey];
        const bv = b[sortKey];
        if (av === bv) return 0;
        return av > bv ? dir : -dir;
      });
    }

    const total = rows.length;
    const pageSize = Math.min(Math.max(Number(req.query.pageSize) || 10, 1), 100);
    const page = Math.max(Number(req.query.page) || 1, 1);
    const totalPages = Math.max(Math.ceil(total / pageSize), 1);
    const start = (page - 1) * pageSize;
    const data = module.tableFeatures?.pagination
      ? rows.slice(start, start + pageSize)
      : rows;

    return res.json({
      success: true,
      data,
      total,
      page,
      pageSize,
      totalPages,
    });
  } catch (err) {
    return res.status(err.status || 500).json({
      success: false,
      error: err.message || "Could not list records.",
    });
  }
});

app.post("/api/portal/:slug/:entity", async (req, res) => {
  try {
    const config = await readPortalConfig(req.params.slug);
    const module = getModule(config, req.params.entity);
    if (!module) {
      return res.status(404).json({
        success: false,
        error: `Entity "${req.params.entity}" not found in portal config.`,
      });
    }

    const parsed = buildRecordSchema(module).safeParse(req.body || {});
    if (!parsed.success) {
      return res.status(400).json({
        success: false,
        error: "Record validation failed.",
        issues: parsed.error.issues,
      });
    }

    const records = await readEntityRecords(config.slug, module.id);
    const record = {
      id: crypto.randomUUID(),
      ...parsed.data,
      createdAt: nowIso(),
      updatedAt: nowIso(),
    };
    records.push(record);
    await writeEntityRecords(config.slug, module.id, records);
    return res.status(201).json({ success: true, data: record });
  } catch (err) {
    return res.status(err.status || 500).json({
      success: false,
      error: err.message || "Could not create record.",
    });
  }
});

app.get("/api/portal/:slug/:entity/:id", async (req, res) => {
  try {
    const config = await readPortalConfig(req.params.slug);
    const module = getModule(config, req.params.entity);
    if (!module) {
      return res.status(404).json({
        success: false,
        error: `Entity "${req.params.entity}" not found in portal config.`,
      });
    }
    const records = await readEntityRecords(config.slug, module.id);
    const record = records.find((item) => item.id === req.params.id);
    if (!record) {
      return res.status(404).json({ success: false, error: "Record not found." });
    }
    return res.json({ success: true, data: record });
  } catch (err) {
    return res.status(err.status || 500).json({
      success: false,
      error: err.message || "Could not read record.",
    });
  }
});

app.put("/api/portal/:slug/:entity/:id", async (req, res) => {
  try {
    const config = await readPortalConfig(req.params.slug);
    const module = getModule(config, req.params.entity);
    if (!module) {
      return res.status(404).json({
        success: false,
        error: `Entity "${req.params.entity}" not found in portal config.`,
      });
    }

    const parsed = buildRecordSchema(module).safeParse(req.body || {});
    if (!parsed.success) {
      return res.status(400).json({
        success: false,
        error: "Record validation failed.",
        issues: parsed.error.issues,
      });
    }

    const records = await readEntityRecords(config.slug, module.id);
    const index = records.findIndex((item) => item.id === req.params.id);
    if (index === -1) {
      return res.status(404).json({ success: false, error: "Record not found." });
    }

    const record = {
      ...records[index],
      ...parsed.data,
      id: records[index].id,
      updatedAt: nowIso(),
    };
    records[index] = record;
    await writeEntityRecords(config.slug, module.id, records);
    return res.json({ success: true, data: record });
  } catch (err) {
    return res.status(err.status || 500).json({
      success: false,
      error: err.message || "Could not update record.",
    });
  }
});

app.delete("/api/portal/:slug/:entity/:id", async (req, res) => {
  try {
    const config = await readPortalConfig(req.params.slug);
    const module = getModule(config, req.params.entity);
    if (!module) {
      return res.status(404).json({
        success: false,
        error: `Entity "${req.params.entity}" not found in portal config.`,
      });
    }
    const records = await readEntityRecords(config.slug, module.id);
    const nextRecords = records.filter((item) => item.id !== req.params.id);
    if (nextRecords.length === records.length) {
      return res.status(404).json({ success: false, error: "Record not found." });
    }
    await writeEntityRecords(config.slug, module.id, nextRecords);
    return res.json({ success: true });
  } catch (err) {
    return res.status(err.status || 500).json({
      success: false,
      error: err.message || "Could not delete record.",
    });
  }
});

// ---------------------------------------------------------------------------
// POST /api/push
// Body: { projectName, repoName?, private? (default true), description? }
// 1) Validate token + project dir exist
// 2) Ensure .gitignore
// 3) Create GitHub repo for authenticated user
// 4) git init -> add -> commit -> push to origin/main
// ---------------------------------------------------------------------------
app.post("/api/push", async (req, res) => {
  const { projectName, repoName, description, private: isPrivate = true } = req.body || {};
  console.log("\n[push] request:", { projectName, repoName, isPrivate });

  // --- Token check first; everything else depends on it. ---
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error("[push] GITHUB_TOKEN missing from environment");
    return res.status(500).json({
      success: false,
      error: "Server missing GITHUB_TOKEN. Set it in server/.env. See .env.example.",
    });
  }

  // --- Input validation ---
  if (!projectName || !NAME_RE.test(projectName)) {
    return res.status(400).json({ success: false, error: "projectName missing or invalid" });
  }
  const finalRepoName = (repoName || projectName).trim();
  if (!NAME_RE.test(finalRepoName)) {
    return res.status(400).json({ success: false, error: "repoName must be alphanumeric, dash, or underscore" });
  }

  const destDir = path.join(OUTPUT_DIR, projectName);
  if (!(await fs.pathExists(destDir))) {
    return res.status(404).json({ success: false, error: `Project "${projectName}" not found in output/` });
  }

  try {
    // --- 1. Write .gitignore (won't overwrite an existing one) ---
    const gitignorePath = path.join(destDir, ".gitignore");
    if (!(await fs.pathExists(gitignorePath))) {
      console.log("[push] writing .gitignore");
      await fs.outputFile(gitignorePath, DEFAULT_GITIGNORE);
    } else {
      console.log("[push] .gitignore already present, leaving it");
    }

    // --- 2. Resolve GitHub user via Octokit ---
    const octokit = new Octokit({ auth: token });
    console.log("[push] auth -> getAuthenticatedUser");
    const { data: user } = await octokit.rest.users.getAuthenticated();
    console.log("[push] authenticated as:", user.login);

    // --- 3. Create repo on GitHub ---
    console.log("[push] creating repo:", finalRepoName, "(private:", isPrivate, ")");
    let repo;
    try {
      const created = await octokit.rest.repos.createForAuthenticatedUser({
        name: finalRepoName,
        description: description || `Generated by platform scaffolder.`,
        private: !!isPrivate,
        auto_init: false,
      });
      repo = created.data;
    } catch (err) {
      // Most common: 422 — repo already exists for this user.
      if (err instanceof RequestError && err.status === 422) {
        return res.status(409).json({
          success: false,
          error: `GitHub repo "${user.login}/${finalRepoName}" already exists. Pick a different name.`,
        });
      }
      throw err;
    }
    console.log("[push] repo created:", repo.html_url);

    // --- 4. git init / add / commit / push ---
    const git = simpleGit(destDir);
    const alreadyRepo = await fs.pathExists(path.join(destDir, ".git"));
    if (!alreadyRepo) {
      console.log("[push] git init");
      await git.init();
    } else {
      console.log("[push] .git already exists, reusing");
    }

    // Set local identity so the commit doesn't fail on machines without global config.
    await git.addConfig("user.email", `${user.id}+${user.login}@users.noreply.github.com`, false, "local");
    await git.addConfig("user.name", user.login, false, "local");

    console.log("[push] staging files");
    await git.add(".");

    console.log("[push] committing");
    await git.commit("Initial commit from platform scaffolder");

    // Force branch name to main for consistency.
    await git.branch(["-M", "main"]);

    // Auth the remote URL with the token. Stored only in this local repo's config.
    const authedUrl = repo.clone_url.replace(
      "https://",
      `https://x-access-token:${token}@`
    );

    // If we reused an existing .git, the remote may already exist — replace it.
    const remotes = await git.getRemotes(true);
    if (remotes.find((r) => r.name === "origin")) {
      await git.removeRemote("origin");
    }
    await git.addRemote("origin", authedUrl);

    console.log("[push] pushing to origin/main");
    await git.push(["-u", "origin", "main"]);

    console.log("[push] done:", repo.html_url);
    return res.json({
      success: true,
      repoUrl: repo.html_url,
      cloneUrl: repo.clone_url,
      owner: user.login,
      repoName: finalRepoName,
      message: `Pushed to ${repo.html_url}`,
    });
  } catch (err) {
    console.error("[push] error:", err);
    // simple-git wraps shell errors; surface what we can.
    const detail = err?.message || "Unknown error during push.";
    return res.status(500).json({ success: false, error: detail });
  }
});

// ---------------------------------------------------------------------------
// Vercel API helper — thin wrapper that handles auth, team scoping, errors.
// ---------------------------------------------------------------------------
const VERCEL_API = "https://api.vercel.com";

async function vercelFetch(pathStr, { method = "GET", body, token, teamId } = {}) {
  const url = new URL(VERCEL_API + pathStr);
  if (teamId) url.searchParams.set("teamId", teamId);

  const res = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(data?.error?.message || `Vercel API ${res.status}`);
    err.status = res.status;
    err.code = data?.error?.code;
    err.data = data;
    throw err;
  }
  return data;
}

// ---------------------------------------------------------------------------
// POST /api/deploy
// Body: { repoName, owner }
// 1) Ensure Vercel project exists (create with Vite build settings, or fetch existing)
// 2) Trigger a production deployment from GitHub main
// 3) Poll deployment status until READY / ERROR / timeout
// ---------------------------------------------------------------------------
app.post("/api/deploy", async (req, res) => {
  const { repoName, owner } = req.body || {};
  console.log("\n[deploy] request:", { repoName, owner });

  const token = process.env.VERCEL_TOKEN;
  const teamId = process.env.VERCEL_TEAM_ID || undefined;

  // --- Token check first ---
  if (!token) {
    console.error("[deploy] VERCEL_TOKEN missing from environment");
    return res.status(500).json({
      success: false,
      error: "Server missing VERCEL_TOKEN. Set it in server/.env. See .env.example.",
    });
  }

  // --- Input validation ---
  if (!repoName || !owner) {
    return res.status(400).json({ success: false, error: "repoName and owner are required" });
  }
  if (!NAME_RE.test(repoName)) {
    return res.status(400).json({ success: false, error: "repoName must be alphanumeric, dash, or underscore" });
  }

  // Vercel requires project names lowercase.
  const projectName = repoName.toLowerCase();

  try {
    // --- 1. Ensure project exists with correct Vite build settings ---
    console.log("[deploy] ensuring Vercel project:", projectName);
    let project;
    try {
      project = await vercelFetch("/v10/projects", {
        method: "POST",
        token,
        teamId,
        body: {
          name: projectName,
          framework: "vite",
          buildCommand: "npm run build",
          outputDirectory: "dist",
          installCommand: "npm install",
          devCommand: "npm run dev",
          gitRepository: {
            type: "github",
            repo: `${owner}/${repoName}`,
          },
        },
      });
      console.log("[deploy] project created:", project.id);
    } catch (err) {
      // Project already exists -> fetch it.
      if (err.status === 409 || /already exists/i.test(err.message || "")) {
        console.log("[deploy] project exists, fetching:", projectName);
        project = await vercelFetch(`/v9/projects/${projectName}`, { token, teamId });
      } else if (
        err.status === 400 &&
        /repository|not found|access/i.test(err.message || "")
      ) {
        return res.status(400).json({
          success: false,
          error:
            "Vercel can't access this GitHub repo. Install the Vercel GitHub app for your account: https://vercel.com/dashboard -> Add New -> Project. Then retry.",
        });
      } else {
        throw err;
      }
    }

    // Vercel returns the GitHub repo's id in project.link after connection.
    const repoId = project?.link?.repoId;
    if (!repoId) {
      return res.status(500).json({
        success: false,
        error:
          "Vercel project has no linked GitHub repoId. The Vercel-GitHub integration may not be installed for this account/repo.",
      });
    }

    // --- 2. Trigger a production deployment from GitHub main ---
    console.log("[deploy] creating deployment from github main");
    const deployment = await vercelFetch("/v13/deployments", {
      method: "POST",
      token,
      teamId,
      body: {
        name: project.name,
        project: project.id,
        target: "production",
        gitSource: {
          type: "github",
          repoId,
          ref: "main",
        },
      },
    });
    console.log("[deploy] deployment queued:", deployment.id, "url:", deployment.url);

    // --- 3. Poll until READY / ERROR / CANCELED / timeout ---
    const TIMEOUT_MS = 120_000; // 2 minutes
    const POLL_MS = 3000;
    const start = Date.now();
    let final = deployment;
    let lastState = final.readyState || "QUEUED";

    while (Date.now() - start < TIMEOUT_MS) {
      await new Promise((r) => setTimeout(r, POLL_MS));
      final = await vercelFetch(`/v13/deployments/${deployment.id}`, { token, teamId });
      lastState = final.readyState || final.status || "UNKNOWN";
      console.log("[deploy]   poll state:", lastState);

      if (lastState === "READY") break;
      if (lastState === "ERROR" || lastState === "CANCELED") {
        return res.status(500).json({
          success: false,
          error: `Vercel build ${lastState}. Check the build logs at https://vercel.com/${owner}/${projectName}/deployments`,
          status: lastState,
        });
      }
    }

    const previewUrl = `https://${final.url || deployment.url}`;
    const deploymentUrl = `https://${projectName}.vercel.app`;
    console.log("[deploy] done:", deploymentUrl, "(state:", lastState + ")");

    return res.json({
      success: true,
      deploymentUrl,
      previewUrl,
      status: lastState,
      message:
        lastState === "READY"
          ? "Deployment is live."
          : "Deployment started — may still be building. Refresh in a moment.",
    });
  } catch (err) {
    console.error("[deploy] error:", err);
    return res.status(500).json({ success: false, error: err.message || "Unknown deploy error" });
  }
});

// ---------------------------------------------------------------------------
// Portal provisioning helpers
// ---------------------------------------------------------------------------
const SUPABASE_MANAGEMENT_API = "https://api.supabase.com";

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function randomSecret(length = 24) {
  return crypto
    .randomBytes(Math.ceil(length * 0.75))
    .toString("base64url")
    .slice(0, length);
}

function sendProgress(res, event) {
  res.write(`data: ${JSON.stringify(event)}\n\n`);
}

async function supabaseManagementFetch(pathStr, { method = "GET", body } = {}) {
  const token = process.env.SUPABASE_ACCESS_TOKEN;
  const res = await fetch(`${SUPABASE_MANAGEMENT_API}${pathStr}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const error = new Error(data.message || data.error || `Supabase API ${res.status}`);
    error.status = res.status;
    error.data = data;
    throw error;
  }
  return data;
}

async function resolveSupabaseOrganizationIdentifier() {
  if (process.env.SUPABASE_ORG_SLUG) {
    return { organization_slug: process.env.SUPABASE_ORG_SLUG };
  }

  const orgId = process.env.SUPABASE_ORG_ID;
  let match;
  try {
    const organizations = await supabaseManagementFetch("/v1/organizations");
    const list = Array.isArray(organizations)
      ? organizations
      : organizations.organizations || organizations.data || [];
    match = list.find((org) => org.id === orgId || org.slug === orgId);
  } catch (error) {
    console.warn("[portal/provision] could not resolve Supabase org slug, falling back to organization_id:", error.message);
  }

  if (match?.slug) {
    return { organization_slug: match.slug };
  }
  return { organization_id: orgId };
}

async function createSupabaseProject(projectName) {
  const dbPassword = randomSecret(32);
  const organizationIdentifier = await resolveSupabaseOrganizationIdentifier();
  const body = {
    name: projectName,
    db_pass: dbPassword,
    ...organizationIdentifier,
    region: process.env.SUPABASE_REGION || "ap-south-1",
    plan: "free",
  };

  const project = await supabaseManagementFetch("/v1/projects", {
    method: "POST",
    body,
  });
  return { project, dbPassword };
}

function healthIsReady(data) {
  if (!data) return false;
  if (data.status === "ACTIVE_HEALTHY") return true;
  if (Array.isArray(data)) {
    return data.length > 0 && data.every((item) => item.status === "ACTIVE_HEALTHY");
  }
  if (Array.isArray(data.services)) {
    return data.services.every((item) => item.status === "ACTIVE_HEALTHY");
  }
  return Object.values(data).some((value) => value === "ACTIVE_HEALTHY");
}

async function waitForSupabaseHealthy(ref) {
  const startedAt = Date.now();
  let lastStatus = "UNKNOWN";

  while (Date.now() - startedAt < 120_000) {
    try {
      const health = await supabaseManagementFetch(`/v1/projects/${ref}/health`);
      if (healthIsReady(health)) return health;
      lastStatus = JSON.stringify(health);
    } catch (error) {
      const project = await supabaseManagementFetch(`/v1/projects/${ref}`);
      if (project.status === "ACTIVE_HEALTHY") return project;
      lastStatus = project.status || error.message;
    }
    await delay(5000);
  }

  throw new Error(`Supabase project did not become ACTIVE_HEALTHY within 120 seconds. Last status: ${lastStatus}`);
}

function extractSupabaseKey(keys, candidates) {
  const list = Array.isArray(keys)
    ? keys
    : keys.api_keys || keys.keys || keys.data || [];

  const match = list.find((item) => {
    const haystack = `${item.name || ""} ${item.type || ""} ${item.role || ""}`.toLowerCase();
    return candidates.some((candidate) => haystack.includes(candidate));
  });

  return (
    match?.api_key ||
    match?.key ||
    match?.value ||
    match?.secret ||
    match?.token ||
    ""
  );
}

async function getSupabaseApiKeys(ref) {
  const keys = await supabaseManagementFetch(`/v1/projects/${ref}/api-keys?reveal=true`);
  const anonKey = extractSupabaseKey(keys, ["anon", "publishable"]);
  const serviceRoleKey = extractSupabaseKey(keys, ["service_role", "secret"]);
  const supabaseUrl = keys.supabase_url || keys.url || `https://${ref}.supabase.co`;

  if (!anonKey || !serviceRoleKey) {
    throw new Error("Could not extract Supabase anon/publishable and service_role/secret keys.");
  }

  return { supabaseUrl, anonKey, serviceRoleKey };
}

async function runSupabaseSql(ref, sql) {
  return supabaseManagementFetch(`/v1/projects/${ref}/database/query`, {
    method: "POST",
    body: { query: sql },
  });
}

// Force PostgREST to reload its schema cache so freshly created tables/columns are
// usable via the REST API. `NOTIFY pgrst, 'reload schema'` is fire-and-forget: on a
// just-created project PostgREST may not be LISTENing yet, so a single NOTIFY can be
// silently dropped and the cache never refreshes (root cause of the recurring
// "Could not find the '<col>' column ... in the schema cache" errors). We therefore
// run it as a dedicated step, a moment after DDL, and retry a few times.
async function reloadPostgrestSchema(ref, { attempts = 4, gapMs = 2500 } = {}) {
  for (let i = 0; i < attempts; i += 1) {
    await delay(gapMs);
    try {
      await runSupabaseSql(ref, "NOTIFY pgrst, 'reload schema';");
    } catch {
      // best-effort; keep retrying
    }
  }
}

async function createSupabaseAdminUser({ supabaseUrl, serviceRoleKey, email, password }) {
  const res = await fetch(`${supabaseUrl}/auth/v1/admin/users`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${serviceRoleKey}`,
      apikey: serviceRoleKey,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      email,
      password,
      email_confirm: true,
      user_metadata: { role: "admin", firstName: "Admin", lastName: "User" },
    }),
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(data.msg || data.message || `Supabase Auth Admin API ${res.status}`);
  }
  return data;
}

async function seedSystemRequiredData({ ref, config, adminEmail, adminAuthUserId }) {
  const organizationId = crypto.randomUUID();
  const companyName = escapeSqlLiteral(
    config.company?.name || config.appName || config.portalName || "Generated Portal"
  );
  const safeAdminEmail = escapeSqlLiteral(adminEmail);
  const authUserValue = adminAuthUserId
    ? `'${escapeSqlLiteral(adminAuthUserId)}'::uuid`
    : "null";

  await runSupabaseSql(
    ref,
    `
insert into organizations (id, name)
values ('${organizationId}'::uuid, '${companyName}')
on conflict (id) do nothing;

insert into organization_users
  (auth_user_id, first_name, last_name, email, organization_id, role, status, account_ids, accounts, is_acknowledged, subscription_id)
values
  (${authUserValue}, 'Admin', 'User', '${safeAdminEmail}', '${organizationId}'::uuid, 'Organization Admin', 'Active', '[]'::jsonb, '[]'::jsonb, true, null)
on conflict (email) do update set
  auth_user_id = excluded.auth_user_id,
  organization_id = excluded.organization_id,
  role = excluded.role,
  status = excluded.status,
  updated_at = now();

update organization_users ou
   set auth_user_id = au.id
  from auth.users au
 where au.email = ou.email
   and ou.email = '${safeAdminEmail}'
   and ou.auth_user_id is null;
`
  );
}

async function copyPortalTemplate({ templateId, projectName, portalConfig }) {
  const srcDir = path.join(TEMPLATES_DIR, templateId);
  const destDir = path.join(OUTPUT_DIR, projectName);

  await fs.ensureDir(OUTPUT_DIR);
  await fs.copy(srcDir, destDir, {
    filter: (src) => !EXCLUDED.has(path.basename(src)),
  });

  await fs.outputJson(path.join(destDir, "src", "portal-config.json"), portalConfig, {
    spaces: 2,
  });
  if (isCrudPortalTemplate(templateId)) {
    await writeCrudPortalSupabaseArtifacts(destDir, portalConfig);
  }
  const gitignorePath = path.join(destDir, ".gitignore");
  if (!(await fs.pathExists(gitignorePath))) {
    await fs.outputFile(gitignorePath, DEFAULT_GITIGNORE);
  }
  return destDir;
}

async function writeCrudPortalSupabaseArtifacts(destDir, portalConfig) {
  const generatedSchema = generateSQL({
    modules: (portalConfig.generatedModules || []).map((module) => ({
      ...module,
      tableName: module.tableName || module.id,
    })),
  });
  await fs.remove(path.join(destDir, "supabase", "generated"));
  await fs.outputFile(
    path.join(destDir, "supabase", "schema.sql"),
    `${portalAdminSystemSchemaSql()}\n\n${generatedSchema}\n`
  );
  await fs.outputFile(
    path.join(destDir, "supabase", "seed.sql"),
    "-- Production-generated portals do not include sample business records.\n-- Provisioning creates only the initial admin user and required system profile.\n"
  );
}

function portalAdminTemplateDir(templateId = "portal-admin") {
  return path.join(TEMPLATES_DIR, templateId);
}

async function hasPortalAdminSupabaseTemplate(templateId) {
  return (
    PORTAL_ADMIN_RUNTIME_TEMPLATE_IDS.has(templateId) &&
    (await fs.pathExists(path.join(portalAdminTemplateDir(templateId), "supabase")))
  );
}

function portalAdminSystemSchemaSql() {
  return `
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS organizations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS organization_users (
  id                        uuid primary key default gen_random_uuid(),
  auth_user_id              uuid unique,
  first_name                text default '',
  last_name                 text default '',
  email                     text not null unique,
  phone_number              text default '',
  country_code              text default '+1',
  organization_id           uuid references organizations(id) on delete cascade,
  role                      text not null default 'Organization User',
  status                    text not null default 'Active',
  account_ids               jsonb not null default '[]',
  accounts                  jsonb not null default '[]',
  is_acknowledged           boolean not null default true,
  is_two_factor_enabled     boolean not null default false,
  requires_password_change  boolean not null default false,
  subscription_id           text,
  profile_photo_url         text default '',
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['organizations','organization_users']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "authenticated_system_access" ON %I;', t);
    EXECUTE format(
      'CREATE POLICY "authenticated_system_access" ON %I FOR ALL TO authenticated USING (true) WITH CHECK (true);', t
    );
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO authenticated;', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO service_role;', t);
  END LOOP;
END $$;
`.trim();
}

function generatedModuleAction(module) {
  return {
    title: module.pluralName,
    description: `Manage ${String(module.pluralName || "records").toLowerCase()} records`,
    icon: module.icon || "Database",
    href: `/organization/crud/${module.id}`,
    gradient: "gradient-primary",
  };
}

function generatedModulePermissions(module) {
  const resource = tableNameForModule(module) || module.id;
  return {
    read: `${resource}:read`,
    write: `${resource}:write`,
    delete: `${resource}:delete`,
  };
}

function buildGeneratedModules(config) {
  return (config.modules || []).map((module) => ({
    id: module.id,
    tableName: module.tableName || tableNameForModule(module),
    singularName: module.singularName,
    pluralName: module.pluralName,
    icon: module.icon || "Database",
    permissions: module.permissions || generatedModulePermissions(module),
    fields: (module.fields || []).map((field) => ({
      key: field.key,
      label: field.label,
      type: field.type,
      required: !!field.required,
      ...(OPTION_FIELD_TYPES.has(field.type) && field.options?.length ? { options: field.options } : {}),
      width: field.width || "full",
      placeholder: field.placeholder || "",
      helpText: field.helpText || "",
    })),
    listColumns: module.listColumns?.length
      ? module.listColumns
      : (module.fields || []).slice(0, 5).map((field) => field.key),
    tableFeatures: {
      sort: module.tableFeatures?.sort !== false,
      filter: module.tableFeatures?.filter !== false,
      search: module.tableFeatures?.search !== false,
      pagination: module.tableFeatures?.pagination !== false,
      export: !!module.tableFeatures?.export,
    },
  }));
}

function buildDashboardConfig(config, generatedModules) {
  const loginPage = config.loginPage || normalizeLoginPage({}, {
    appName: config.appName,
    industry: config.industry,
    footerText: config.footer?.text,
  });
  const actions = generatedModules.map(generatedModuleAction);
  const primaryActions = actions.slice(0, Math.min(3, actions.length));
  const secondaryActions = actions.slice(primaryActions.length);

  return {
    enabled: config.dashboard?.enabled !== false,
    template: config.dashboard?.template || "stats-overview",
    style: config.dashboard?.style || config.industry || "generic",
    heroTitle: loginPage.headline,
    heroSubtitle: loginPage.description,
    primaryActions,
    secondaryActions,
    sectionTitle: secondaryActions.length ? "More Modules" : "Workspace Modules",
    emptyTitle: "No modules configured",
    emptyDescription: "Add CRUD modules in the platform wizard to populate this dashboard.",
  };
}

function auditPortalRuntimeConfig(config) {
  const errors = [];
  const warnings = [];
  const industry = config.industry || "generic";
  const text = JSON.stringify(config || {}).toLowerCase();
  const bannedHealthcareTerms = [
    "wc-health",
    "aidin",
    "hipaa",
    "payer",
    "clinic",
    "patient records",
    "patients & claims",
    "claim status",
    "demo health",
  ];

  if (!config.appName && !config.portalName) {
    errors.push("Runtime config is missing appName/portalName.");
  }
  if (!config.loginPage?.headline || !config.loginPage?.description) {
    errors.push("Runtime config is missing login page copy.");
  }
  if (!Array.isArray(config.navigation) || config.navigation.length === 0) {
    errors.push("Runtime config has no navigation items.");
  }
  if (!Array.isArray(config.generatedModules) || config.generatedModules.length === 0) {
    errors.push("Runtime config has no generated modules.");
  }
  if (industry !== "healthcare") {
    const matches = bannedHealthcareTerms.filter((term) => text.includes(term));
    if (matches.length) {
      errors.push(`Runtime config contains template/healthcare leakage: ${matches.join(", ")}.`);
    }
  }
  if (!config.logo?.src && !config.logo?.text) {
    warnings.push("No uploaded logo found. Generated project will use fallback initials.");
  }

  return { errors, warnings };
}

async function buildPortalAdminRuntimeConfig(config) {
  const defaultConfigPath = path.join(portalAdminTemplateDir(config.templateId), "src", "portal-config.json");
  const defaultConfig = await fs.readJson(defaultConfigPath);
  const generatedModules = buildGeneratedModules(config);

  const generatedNavItems = generatedModules.map((module) => ({
    label: module.pluralName,
    icon: module.icon || "Database",
    path: `/organization/crud/${module.id}`,
    permission: "dashboard:read",
  }));

  const navigation = [
    {
      label: "Dashboard",
      icon: "LayoutDashboard",
      path: "/organization/dashboard",
      permission: "dashboard:read",
    },
    ...generatedNavItems,
  ];
  if (config.profile?.enabled !== false) {
    navigation.push({
      label: "Profile",
      icon: "UserRound",
      path: "/organization/profile",
      permission: "dashboard:read",
    });
  }

  const loginPage = normalizeLoginPage(config.loginPage || {}, {
    appName: config.appName,
    industry: config.industry,
    footerText: config.footer?.text,
  });
  const themeTokens = themeTokensFromColor(config.themeColor || "#2563eb");
  const logoText = config.logoText || initialsForName(config.appName || config.portalName);

  return {
    ...defaultConfig,
    appName: config.appName,
    portalName: config.appName || config.portalName || defaultConfig.portalName,
    industry: config.industry || "generic",
    themePreset: config.themePreset || "custom",
    runtime: {
      ...(defaultConfig.runtime || {}),
      legacyRoutesEnabled: false,
      blockMobile: false,
    },
    auth: config.auth || defaultConfig.auth,
    footer: {
      ...(defaultConfig.footer || {}),
      ...(config.footer || {}),
      text: config.footer?.text || loginPage.footerText,
    },
    company: {
      name: config.company?.name || config.appName,
      website: config.company?.website || "",
      supportEmail: config.company?.supportEmail || "",
      address: config.company?.address || "",
    },
    loginPage,
    dashboard: buildDashboardConfig({ ...config, loginPage }, generatedModules),
    navigation,
    generatedModules,
    entities: [],
    logo: {
      ...(defaultConfig.logo || {}),
      src: config.logoUrl || "",
      text: logoText,
      alt: config.appName || defaultConfig.logo?.alt || defaultConfig.portalName,
    },
    theme: {
      ...(defaultConfig.theme || {}),
      mode: config.themeMode || defaultConfig.theme?.mode || "system",
      name: config.themePreset || "custom",
      primary: config.themeColor || "#2563eb",
      primaryHover: themeTokens["brand-primary-hover"],
      primaryLight: themeTokens["brand-primary-light"],
      accent: themeTokens["brand-accent"],
      tokens: {
        ...(defaultConfig.theme?.tokens || {}),
        ...themeTokens,
      },
    },
  };
}

function buildTopbarRuntimeConfig(config) {
  const generatedModules = buildGeneratedModules(config);
  const loginPage = normalizeLoginPage(config.loginPage || {}, {
    appName: config.appName,
    industry: config.industry,
    footerText: config.footer?.text,
  });
  const themeColor = config.themeColor || "#2563eb";
  const themeTokens = themeTokensFromColor(themeColor);
  const logoInitials = config.logoText || initialsForName(config.appName || config.portalName);

  return {
    portalName: config.portalName || config.appName,
    appName: config.appName,
    industry: config.industry || "generic",
    logo: config.logoUrl || "",
    logoInitials,
    theme: {
      primary: themeColor,
      primaryHover: themeTokens["brand-primary-hover"],
      primaryLight: themeTokens["brand-primary-light"],
      accent: themeTokens["brand-accent"],
    },
    loginPage: {
      ...loginPage,
      features: (loginPage.features || []).map((feature, index) => ({
        ...feature,
        icon: feature.icon || (index === 0 ? "ShieldCheck" : "LayoutGrid"),
      })),
    },
    routes: {
      loginPath: "/login",
      appBasePath: "/organization",
      dashboardPath: "/organization/dashboard",
      profilePath: "/organization/profile",
    },
    dashboard: {
      enabled: config.dashboard?.enabled !== false,
      label: "Dashboard",
      icon: "LayoutDashboard",
      title: config.appName,
      description: `${config.appName} operational overview`,
      widgets: ["module-counts", "currency-sum", "status-breakdown", "created-trend"],
    },
    footer: {
      text: config.footer?.text || loginPage.footerText,
    },
    company: {
      name: config.company?.name || config.appName,
      website: config.company?.website || "",
      address: config.company?.address || "",
    },
    support: {
      email: config.company?.supportEmail || "",
      phone: "",
      helpUrl: config.company?.website || "",
    },
    featureFlags: {
      profile: config.profile?.enabled !== false,
      signup: config.auth?.screens?.signup === true,
    },
    generatedModules,
  };
}

async function pushGeneratedProject({ projectName, repoName, description, isPrivate = true }) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error("Server missing GITHUB_TOKEN. Set it in server/.env.");
  }

  const finalRepoName = repoName || projectName;
  const destDir = path.join(OUTPUT_DIR, projectName);
  const octokit = new Octokit({ auth: token });
  const { data: user } = await octokit.rest.users.getAuthenticated();

  let repo;
  try {
    const created = await octokit.rest.repos.createForAuthenticatedUser({
      name: finalRepoName,
      description: description || "Generated by platform scaffolder.",
      private: !!isPrivate,
      auto_init: false,
    });
    repo = created.data;
  } catch (err) {
    if (err instanceof RequestError && err.status === 422) {
      throw new Error(`GitHub repo "${user.login}/${finalRepoName}" already exists. Pick a different name.`);
    }
    throw err;
  }

  const git = simpleGit(destDir);
  if (!(await fs.pathExists(path.join(destDir, ".git")))) {
    await git.init();
  }
  await git.addConfig("user.email", `${user.id}+${user.login}@users.noreply.github.com`, false, "local");
  await git.addConfig("user.name", user.login, false, "local");
  await git.add(".");
  await git.commit("Initial commit from platform scaffolder");
  await git.branch(["-M", "main"]);

  const authedUrl = repo.clone_url.replace(
    "https://",
    `https://x-access-token:${token}@`
  );
  const remotes = await git.getRemotes(true);
  if (remotes.find((remote) => remote.name === "origin")) {
    await git.removeRemote("origin");
  }
  await git.addRemote("origin", authedUrl);
  await git.push(["-u", "origin", "main"]);

  return {
    repoUrl: repo.html_url,
    cloneUrl: repo.clone_url,
    owner: user.login,
    repoName: finalRepoName,
  };
}

async function upsertVercelEnv({ projectIdOrName, token, teamId, key, value }) {
  return vercelFetch(`/v10/projects/${encodeURIComponent(projectIdOrName)}/env?upsert=true`, {
    method: "POST",
    token,
    teamId,
    body: {
      key,
      value,
      type: "encrypted",
      target: ["production", "preview", "development"],
      comment: "Generated by platform portal provisioning.",
    },
  });
}

async function deployGeneratedProject({ repoName, owner, env = {} }) {
  const token = process.env.VERCEL_TOKEN;
  const teamId = process.env.VERCEL_TEAM_ID || undefined;
  if (!token) {
    throw new Error("Server missing VERCEL_TOKEN. Set it in server/.env.");
  }

  const projectName = repoName.toLowerCase();
  let project;
  try {
    project = await vercelFetch("/v10/projects", {
      method: "POST",
      token,
      teamId,
      body: {
        name: projectName,
        framework: "vite",
        buildCommand: "npm run build",
        outputDirectory: "dist",
        installCommand: "npm install",
        devCommand: "npm run dev",
        gitRepository: {
          type: "github",
          repo: `${owner}/${repoName}`,
        },
      },
    });
  } catch (err) {
    if (err.status === 409 || /already exists/i.test(err.message || "")) {
      project = await vercelFetch(`/v9/projects/${projectName}`, { token, teamId });
    } else {
      throw err;
    }
  }

  for (const [key, value] of Object.entries(env)) {
    await upsertVercelEnv({
      projectIdOrName: project.id || project.name || projectName,
      token,
      teamId,
      key,
      value,
    });
  }

  const repoId = project?.link?.repoId;
  if (!repoId) {
    throw new Error("Vercel project has no linked GitHub repoId. Install or refresh the Vercel GitHub integration for this repo.");
  }

  const deployment = await vercelFetch("/v13/deployments", {
    method: "POST",
    token,
    teamId,
    body: {
      name: project.name,
      project: project.id,
      target: "production",
      gitSource: {
        type: "github",
        repoId,
        ref: "main",
      },
    },
  });

  const startedAt = Date.now();
  let final = deployment;
  let lastState = final.readyState || "QUEUED";
  while (Date.now() - startedAt < 120_000) {
    await delay(3000);
    final = await vercelFetch(`/v13/deployments/${deployment.id}`, { token, teamId });
    lastState = final.readyState || final.status || "UNKNOWN";
    if (lastState === "READY") break;
    if (lastState === "ERROR" || lastState === "CANCELED") {
      throw new Error(`Vercel build ${lastState}. Check the build logs.`);
    }
  }

  return {
    deploymentUrl: `https://${projectName}.vercel.app`,
    previewUrl: `https://${final.url || deployment.url}`,
    status: lastState,
  };
}

// ---------------------------------------------------------------------------
// POST /api/portal/provision
// Streams text/event-stream progress while provisioning Supabase, scaffolding,
// pushing to GitHub, and deploying to Vercel. Existing landing endpoints are
// intentionally untouched.
// ---------------------------------------------------------------------------
app.post("/api/portal/provision", async (req, res) => {
  const { templateId, projectName, portalConfig } = req.body || {};
  const resolvedTemplateId = validateResolvedTemplateId(templateId);
  const safeProjectName = safePortalSlug(projectName);

  if (!templateId || !resolvedTemplateId || !safeProjectName) {
    return res.status(400).json({
      success: false,
      error: "templateId and projectName are required and must be URL-safe.",
    });
  }

  const srcDir = path.join(TEMPLATES_DIR, resolvedTemplateId);
  const destDir = path.join(OUTPUT_DIR, safeProjectName);
  if (!(await fs.pathExists(srcDir))) {
    return res.status(404).json({
      success: false,
      error: `Template "${templateId}" not found in templates/.`,
    });
  }
  if (await fs.pathExists(destDir)) {
    return res.status(409).json({
      success: false,
      error: `Output "${safeProjectName}" already exists. Pick a different project name.`,
    });
  }

  const missingEnv = [];
  if (!process.env.SUPABASE_ACCESS_TOKEN) missingEnv.push("SUPABASE_ACCESS_TOKEN");
  if (!process.env.SUPABASE_ORG_ID && !process.env.SUPABASE_ORG_SLUG) {
    missingEnv.push("SUPABASE_ORG_ID");
  }
  if (!process.env.GITHUB_TOKEN) missingEnv.push("GITHUB_TOKEN");
  if (!process.env.VERCEL_TOKEN) missingEnv.push("VERCEL_TOKEN");
  if (missingEnv.length) {
    return res.status(500).json({
      success: false,
      error: `Missing server environment variables: ${missingEnv.join(", ")}`,
    });
  }

  let normalizedConfig;
  let usesStaticPortalAdminTemplate = false;
  let usesTopbarTemplate = false;
  let runtimeConfig;
  let readinessWarnings = [];
  try {
    normalizedConfig = normalizePortalConfig({
      ...(portalConfig || {}),
      templateId: resolvedTemplateId,
      slug: safeProjectName,
      portalName: portalConfig?.portalName || safeProjectName,
    });
    normalizedConfig.modules = normalizedConfig.modules.map((module) => ({
      ...module,
      tableName: tableNameForModule(module),
    }));
    usesStaticPortalAdminTemplate = await hasPortalAdminSupabaseTemplate(resolvedTemplateId);
    usesTopbarTemplate = resolvedTemplateId === TOPBAR_TEMPLATE_ID;
    runtimeConfig = usesStaticPortalAdminTemplate
      ? await buildPortalAdminRuntimeConfig(normalizedConfig)
      : usesTopbarTemplate
        ? buildTopbarRuntimeConfig(normalizedConfig)
        : normalizedConfig;
    const readiness = usesStaticPortalAdminTemplate
      ? auditPortalRuntimeConfig(runtimeConfig)
      : { errors: [], warnings: [] };
    if (readiness.errors.length) {
      throw new Error(readiness.errors.join(" "));
    }
    readinessWarnings = readiness.warnings;
  } catch (err) {
    const issues = err?.issues?.map((issue) => issue.message).join("; ");
    return res.status(400).json({
      success: false,
      error: issues || err.message || "Invalid portal config.",
    });
  }

  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
  });

  try {
    sendProgress(res, { step: 1, status: "running", message: "Creating database..." });
    const { project } = await createSupabaseProject(safeProjectName);
    const ref = project.ref || project.id;
    if (!ref) throw new Error("Supabase project response did not include a ref.");
    await waitForSupabaseHealthy(ref);
    const keys = await getSupabaseApiKeys(ref);
    sendProgress(res, { step: 1, status: "done", message: "Database ready." });

    sendProgress(res, { step: 2, status: "running", message: "Creating tables..." });
    if (isCrudPortalTemplate(resolvedTemplateId)) {
      await runSupabaseSql(ref, portalAdminSystemSchemaSql());
      await runSupabaseSql(ref, generateSQL(normalizedConfig));
    } else {
      await runSupabaseSql(ref, generateSQL(normalizedConfig));
    }
    sendProgress(res, { step: 2, status: "done", message: "Tables created." });

    // Refresh PostgREST schema cache now that PostgREST is healthy and listening,
    // so the new tables/columns are immediately queryable from the deployed portal.
    await reloadPostgrestSchema(ref);

    const adminEmail = DEFAULT_ADMIN_EMAIL;
    const adminPassword = DEFAULT_ADMIN_PASSWORD;
    sendProgress(res, { step: 3, status: "running", message: "Configuring authentication..." });
    const adminUser = await createSupabaseAdminUser({
      supabaseUrl: keys.supabaseUrl,
      serviceRoleKey: keys.serviceRoleKey,
      email: adminEmail,
      password: adminPassword,
    });
    sendProgress(res, { step: 3, status: "done", message: "Authentication configured." });

    sendProgress(res, { step: 4, status: "running", message: "Adding system-required data..." });
    await seedSystemRequiredData({
      ref,
      config: normalizedConfig,
      adminEmail,
      adminAuthUserId: adminUser?.id || adminUser?.user?.id || adminUser?.data?.id || "",
    });
    sendProgress(res, { step: 4, status: "done", message: "System data added. Business tables are empty." });

    sendProgress(res, { step: 5, status: "running", message: "Building portal from template..." });
    await copyPortalTemplate({
      templateId: resolvedTemplateId,
      projectName: safeProjectName,
      portalConfig: runtimeConfig,
    });
    sendProgress(res, { step: 5, status: "done", message: "Portal template ready." });

    sendProgress(res, { step: 6, status: "running", message: "Publishing to GitHub..." });
    const repo = await pushGeneratedProject({
      projectName: safeProjectName,
      repoName: safeProjectName,
      description: `${normalizedConfig.appName} generated portal`,
      isPrivate: true,
    });
    sendProgress(res, { step: 6, status: "done", message: "GitHub repository ready." });

    sendProgress(res, { step: 7, status: "running", message: "Deploying..." });
    const deployment = await deployGeneratedProject({
      repoName: repo.repoName,
      owner: repo.owner,
      env: {
        VITE_SUPABASE_URL: keys.supabaseUrl,
        VITE_SUPABASE_ANON_KEY: keys.anonKey,
      },
    });

    const basePortalAdminTables = [
      "organizations",
      "accounts",
      "organization_users",
      "payers",
      "patients",
      "patient_notes",
      "batches",
      "claims",
    ];
    const generatedTableNames = normalizedConfig.modules.map((module) => module.tableName);

    sendProgress(res, {
      step: 7,
      status: "complete",
      message: "Portal ready!",
      data: {
        liveUrl: deployment.deploymentUrl,
        repoUrl: repo.repoUrl,
        supabaseUrl: keys.supabaseUrl,
        supabaseProjectRef: ref,
        adminEmail,
        adminPassword,
        tables: usesStaticPortalAdminTemplate && normalizedConfig.industry === "healthcare"
          ? [...basePortalAdminTables, ...generatedTableNames]
          : generatedTableNames,
        sampleRowsPerTable: 0,
        sampleRowsPerGeneratedTable: 0,
        sampleDataSummary: "No business records seeded. Tables start empty except admin user, organization profile, and required system settings.",
        readinessWarnings,
        projectName: safeProjectName,
      },
    });
    res.end();
  } catch (err) {
    console.error("[portal/provision] error:", err);
    sendProgress(res, {
      status: "error",
      message: err.message || "Portal provisioning failed.",
      error: err.message || "Portal provisioning failed.",
    });
    res.end();
  }
});

function demoField(label, type, options = {}) {
  return {
    id: crypto.randomUUID(),
    key: options.key || slugify(label).replace(/-/g, "_"),
    label,
    type,
    required: !!options.required,
    width: options.width || "full",
    placeholder: options.placeholder || "",
    helpText: options.helpText || "",
    options: options.options || [],
    settings: options.settings || {},
    features: { filter: options.filter !== false },
  };
}

function demoPortalConfig() {
  const agents = {
    id: "agents",
    singularName: "Agent",
    pluralName: "Agents",
    icon: "Users",
    fields: [
      demoField("Agent Name", "text", { key: "name", required: true, width: "half" }),
      demoField("Email", "email", { key: "email", required: true, width: "half" }),
      demoField("License Number", "text", { key: "license_number", width: "half" }),
      demoField("Region", "select", {
        key: "region",
        required: true,
        width: "half",
        options: ["North", "South", "East", "West", "Central"],
      }),
      demoField("Active", "toggle", { key: "active", width: "third" }),
      demoField("Joined On", "date", { key: "joined_on", width: "third" }),
      demoField("Portfolio Value", "currency", { key: "portfolio_value", width: "third" }),
      demoField("Rating", "number", {
        key: "rating",
        width: "third",
        settings: { min: 1, max: 5 },
      }),
      demoField("Avatar", "image", { key: "avatar", width: "third", filter: false }),
      demoField("Specialties", "tags", { key: "specialties", width: "full" }),
    ],
    listColumns: ["name", "region", "portfolio_value", "active"],
    tableFeatures: { sort: true, filter: true, search: true, pagination: true, export: true },
  };

  const policies = {
    id: "policies",
    singularName: "Policy",
    pluralName: "Policies",
    icon: "FileText",
    fields: [
      demoField("Policy Number", "text", { key: "policy_number", required: true, width: "half" }),
      demoField("Holder Name", "text", { key: "holder_name", required: true, width: "half" }),
      demoField("Holder Email", "email", { key: "holder_email", width: "half" }),
      demoField("Product", "select", {
        key: "product",
        required: true,
        width: "half",
        options: ["Health", "Motor", "Life", "Travel", "Property"],
      }),
      demoField("Premium", "currency", { key: "premium", width: "third" }),
      demoField("Sum Insured", "currency", { key: "sum_insured", width: "third" }),
      demoField("Start Date", "date", { key: "start_date", width: "third" }),
      demoField("Renewal Date", "date", { key: "renewal_date", width: "third" }),
      demoField("Status", "select", {
        key: "status",
        width: "third",
        options: ["Active", "Pending", "Lapsed", "Claimed"],
      }),
      demoField("Documents", "file", { key: "documents", width: "third", filter: false }),
      demoField("Nominee", "text", { key: "nominee", width: "half" }),
      demoField("Auto Renew", "checkbox", { key: "auto_renew", width: "half" }),
    ],
    listColumns: ["policy_number", "holder_name", "product", "premium", "status"],
    tableFeatures: { sort: true, filter: true, search: true, pagination: true, export: true },
  };

  const claims = {
    id: "claims",
    singularName: "Claim",
    pluralName: "Claims",
    icon: "ClipboardList",
    fields: [
      demoField("Claim Number", "text", { key: "claim_number", required: true, width: "half" }),
      demoField("Policy Number", "text", { key: "policy_number", required: true, width: "half" }),
      demoField("Claimant Name", "text", { key: "claimant_name", required: true, width: "half" }),
      demoField("Amount", "currency", { key: "amount", width: "half" }),
      demoField("Incident Date", "date", { key: "incident_date", width: "third" }),
      demoField("Status", "select", {
        key: "status",
        width: "third",
        options: ["Submitted", "Under Review", "Approved", "Rejected", "Paid"],
      }),
      demoField("Urgent", "checkbox", { key: "urgent", width: "third" }),
      demoField("Notes", "textarea", { key: "notes", width: "full" }),
    ],
    listColumns: ["claim_number", "policy_number", "claimant_name", "amount", "status"],
    tableFeatures: { sort: true, filter: true, search: true, pagination: true, export: true },
  };

  return normalizePortalConfig({
    version: 1,
    templateId: "insurance-portal",
    slug: "demo-admin",
    portalName: "demo-admin",
    appName: "Acme Insurance Admin",
    type: "insurance",
    themeColor: "#059669",
    logoUrl: "",
    auth: {
      screens: { login: true, signup: true, forgotPassword: true },
      method: "email-password",
    },
    dashboard: { enabled: true, template: "stats-overview" },
    profile: { enabled: true },
    modules: [agents, policies, claims],
  });
}

function withId(record) {
  return {
    id: crypto.randomUUID(),
    ...record,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  };
}

function demoPortalData() {
  return {
    agents: [
      withId({ name: "Aarav Mehta", email: "aarav.mehta@acme.test", license_number: "AG-MH-2041", region: "West", active: true, joined_on: "2022-03-14", portfolio_value: 8200000, rating: 5, avatar: "", specialties: ["Health", "Life"] }),
      withId({ name: "Ananya Rao", email: "ananya.rao@acme.test", license_number: "AG-KA-1172", region: "South", active: true, joined_on: "2021-11-08", portfolio_value: 10400000, rating: 5, avatar: "", specialties: ["Motor", "Travel"] }),
      withId({ name: "Ishaan Kapoor", email: "ishaan.kapoor@acme.test", license_number: "AG-DL-9044", region: "North", active: true, joined_on: "2023-01-20", portfolio_value: 6100000, rating: 4, avatar: "", specialties: ["Life"] }),
      withId({ name: "Meera Iyer", email: "meera.iyer@acme.test", license_number: "AG-TN-5580", region: "South", active: false, joined_on: "2020-06-12", portfolio_value: 7300000, rating: 4, avatar: "", specialties: ["Health", "Property"] }),
      withId({ name: "Kabir Singh", email: "kabir.singh@acme.test", license_number: "AG-PB-7719", region: "North", active: true, joined_on: "2022-09-01", portfolio_value: 5600000, rating: 3, avatar: "", specialties: ["Motor"] }),
      withId({ name: "Priya Nair", email: "priya.nair@acme.test", license_number: "AG-KL-3821", region: "South", active: true, joined_on: "2019-04-18", portfolio_value: 12900000, rating: 5, avatar: "", specialties: ["Health", "Travel"] }),
      withId({ name: "Rohan Desai", email: "rohan.desai@acme.test", license_number: "AG-GJ-2398", region: "West", active: true, joined_on: "2023-07-05", portfolio_value: 4200000, rating: 4, avatar: "", specialties: ["Property"] }),
      withId({ name: "Saanvi Gupta", email: "saanvi.gupta@acme.test", license_number: "AG-UP-6140", region: "Central", active: true, joined_on: "2021-02-27", portfolio_value: 9100000, rating: 5, avatar: "", specialties: ["Life", "Health"] }),
    ],
    policies: [
      withId({ policy_number: "POL-2026-1001", holder_name: "Nikhil Verma", holder_email: "nikhil.verma@example.test", product: "Health", premium: 24500, sum_insured: 800000, start_date: "2026-01-05", renewal_date: "2027-01-05", status: "Active", documents: "health-policy-1001.pdf", nominee: "Ritu Verma", auto_renew: true }),
      withId({ policy_number: "POL-2026-1002", holder_name: "Diya Shah", holder_email: "diya.shah@example.test", product: "Motor", premium: 18600, sum_insured: 650000, start_date: "2026-02-11", renewal_date: "2027-02-11", status: "Active", documents: "motor-policy-1002.pdf", nominee: "Kunal Shah", auto_renew: true }),
      withId({ policy_number: "POL-2026-1003", holder_name: "Arjun Menon", holder_email: "arjun.menon@example.test", product: "Life", premium: 42000, sum_insured: 2500000, start_date: "2025-10-20", renewal_date: "2026-10-20", status: "Pending", documents: "life-policy-1003.pdf", nominee: "Lakshmi Menon", auto_renew: false }),
      withId({ policy_number: "POL-2026-1004", holder_name: "Sara Khan", holder_email: "sara.khan@example.test", product: "Travel", premium: 7200, sum_insured: 500000, start_date: "2026-03-02", renewal_date: "2026-06-02", status: "Active", documents: "travel-policy-1004.pdf", nominee: "Imran Khan", auto_renew: false }),
      withId({ policy_number: "POL-2026-1005", holder_name: "Vivaan Joshi", holder_email: "vivaan.joshi@example.test", product: "Property", premium: 56000, sum_insured: 4200000, start_date: "2025-12-15", renewal_date: "2026-12-15", status: "Active", documents: "property-policy-1005.pdf", nominee: "Maya Joshi", auto_renew: true }),
      withId({ policy_number: "POL-2026-1006", holder_name: "Tara Bose", holder_email: "tara.bose@example.test", product: "Health", premium: 31200, sum_insured: 1200000, start_date: "2026-04-01", renewal_date: "2027-04-01", status: "Active", documents: "health-policy-1006.pdf", nominee: "Dev Bose", auto_renew: true }),
      withId({ policy_number: "POL-2026-1007", holder_name: "Aditya Kulkarni", holder_email: "aditya.kulkarni@example.test", product: "Motor", premium: 15800, sum_insured: 550000, start_date: "2025-08-18", renewal_date: "2026-08-18", status: "Lapsed", documents: "motor-policy-1007.pdf", nominee: "Neha Kulkarni", auto_renew: false }),
      withId({ policy_number: "POL-2026-1008", holder_name: "Zoya Ali", holder_email: "zoya.ali@example.test", product: "Life", premium: 38500, sum_insured: 1800000, start_date: "2026-05-10", renewal_date: "2027-05-10", status: "Active", documents: "life-policy-1008.pdf", nominee: "Amin Ali", auto_renew: true }),
    ],
    claims: [
      withId({ claim_number: "CLM-9001", policy_number: "POL-2026-1001", claimant_name: "Nikhil Verma", amount: 86000, incident_date: "2026-02-14", status: "Under Review", urgent: false, notes: "Hospitalization claim under review." }),
      withId({ claim_number: "CLM-9002", policy_number: "POL-2026-1002", claimant_name: "Diya Shah", amount: 42000, incident_date: "2026-03-08", status: "Approved", urgent: false, notes: "Garage estimate verified." }),
      withId({ claim_number: "CLM-9003", policy_number: "POL-2026-1004", claimant_name: "Sara Khan", amount: 18000, incident_date: "2026-03-21", status: "Paid", urgent: false, notes: "Flight delay reimbursement paid." }),
      withId({ claim_number: "CLM-9004", policy_number: "POL-2026-1005", claimant_name: "Vivaan Joshi", amount: 240000, incident_date: "2026-01-19", status: "Submitted", urgent: true, notes: "Water damage assessment pending." }),
      withId({ claim_number: "CLM-9005", policy_number: "POL-2026-1006", claimant_name: "Tara Bose", amount: 67000, incident_date: "2026-04-18", status: "Under Review", urgent: true, notes: "Cashless approval requested." }),
      withId({ claim_number: "CLM-9006", policy_number: "POL-2026-1007", claimant_name: "Aditya Kulkarni", amount: 31000, incident_date: "2026-02-02", status: "Rejected", urgent: false, notes: "Policy lapsed at incident date." }),
      withId({ claim_number: "CLM-9007", policy_number: "POL-2026-1008", claimant_name: "Zoya Ali", amount: 125000, incident_date: "2026-05-14", status: "Approved", urgent: false, notes: "Documents complete." }),
      withId({ claim_number: "CLM-9008", policy_number: "POL-2026-1003", claimant_name: "Arjun Menon", amount: 54000, incident_date: "2026-01-28", status: "Submitted", urgent: false, notes: "Waiting for medical reports." }),
    ],
  };
}

async function ensureDemoPortal() {
  await fs.ensureDir(PORTALS_DIR);
  const entries = await fs.readdir(PORTALS_DIR);
  if (entries.length > 0) return;

  const config = demoPortalConfig();
  await fs.outputJson(portalConfigPath(config.slug), config, { spaces: 2 });
  const data = demoPortalData();
  for (const [entity, records] of Object.entries(data)) {
    await fs.outputJson(portalDataPath(config.slug, entity), records, { spaces: 2 });
  }
  console.log(`[server] seeded demo portal: ${config.slug}`);
}

try {
  await ensureDemoPortal();
} catch (err) {
  console.error("[server] demo portal seed failed:", err);
}

const PORT = process.env.PORT || 5174;
app.listen(PORT, () => {
  console.log(`[server] listening on http://localhost:${PORT}`);
  console.log(`[server] templates dir: ${TEMPLATES_DIR}`);
  console.log(`[server] output dir:    ${OUTPUT_DIR}`);
  console.log(`[server] portals dir:   ${PORTALS_DIR}`);
  console.log(
    `[server] GITHUB_TOKEN: ${process.env.GITHUB_TOKEN ? "present" : "MISSING (push endpoint will 500)"}`
  );
  console.log(
    `[server] VERCEL_TOKEN: ${process.env.VERCEL_TOKEN ? "present" : "MISSING (deploy endpoint will 500)"}`
  );
  console.log(
    `[server] GEMINI_API_KEY: ${process.env.GEMINI_API_KEY ? "present" : "MISSING (generate-config endpoint will 500)"}`
  );
  console.log(
    `[server] SUPABASE_ACCESS_TOKEN: ${process.env.SUPABASE_ACCESS_TOKEN ? "present" : "MISSING (portal provision endpoint will 500)"}`
  );
});
