/**
 * @fileoverview Service Type Code (STC) options for eligibility/benefits verification.
 *
 * These codes correspond to the ANSI X12N 271 standard service type codes
 * used in healthcare eligibility inquiries.
 *
 * @module constants/stc-codes
 */

export const STC_CODE_OPTIONS = [
    { value: "1", label: "1 - Medical Care" },
    { value: "2", label: "2 - Surgical" },
    { value: "3", label: "3 - Consultation" },
    { value: "4", label: "4 - Diagnostic X-Ray" },
    { value: "5", label: "5 - Diagnostic Lab" },
    { value: "6", label: "6 - Radiation Therapy" },
    { value: "7", label: "7 - Anesthesia" },
    { value: "8", label: "8 - Hospitalization" },
    { value: "9", label: "9 - Other Medical" },
    { value: "12", label: "12 - Durable Medical Equipment Purchase" },
    { value: "13", label: "13 - Ambulatory Service Center Facility" },
    { value: "17", label: "17 - Renal Supplies in the Home" },
    { value: "18", label: "18 - Durable Medical Equipment Rental" },
    { value: "19", label: "19 - POS / Point of Service" },
    { value: "22", label: "22 - Social Work" },
    { value: "30", label: "30 - Health Benefit Plan Coverage" },
    { value: "32", label: "32 - Pre-existing Condition" },
    { value: "33", label: "33 - Chiropractic" },
    { value: "35", label: "35 - Dental Care" },
    { value: "40", label: "40 - Oral Surgery" },
    { value: "42", label: "42 - Home Health Care" },
    { value: "45", label: "45 - Hospice" },
    { value: "47", label: "47 - Hospital" },
    { value: "48", label: "48 - Hospital - Inpatient" },
    { value: "50", label: "50 - Hospital - Outpatient" },
    { value: "51", label: "51 - Hospital - Emergency Medical" },
    { value: "52", label: "52 - Hospital - Emergency Room" },
    { value: "53", label: "53 - Hospital - Ambulatory Surgical" },
    { value: "56", label: "56 - Skilled Nursing Facility" },
    { value: "60", label: "60 - General Benefits" },
    { value: "61", label: "61 - In-vitro Fertilization" },
    { value: "62", label: "62 - MRI/CAT Scan" },
    { value: "64", label: "64 - Pneumonia Vaccine" },
    { value: "65", label: "65 - Newborn Care" },
    { value: "67", label: "67 - Smoking Cessation" },
    { value: "68", label: "68 - Well Baby Care" },
    { value: "69", label: "69 - Maternity" },
    { value: "70", label: "70 - Transplants" },
    { value: "71", label: "71 - Eyewear and Accessories" },
    { value: "73", label: "73 - Diagnostic Medical" },
    { value: "74", label: "74 - Long Term Care" },
    { value: "75", label: "75 - Cancer" },
    { value: "76", label: "76 - Dialysis" },
    { value: "78", label: "78 - Chemotherapy" },
    { value: "79", label: "79 - Cataract / Eye Procedures" },
    { value: "80", label: "80 - Immunizations" },
    { value: "81", label: "81 - Routine Physical" },
    { value: "82", label: "82 - Family Planning" },
    { value: "83", label: "83 - Infertility" },
    { value: "84", label: "84 - Diagnostic Dental" },
    { value: "86", label: "86 - Emergency Services" },
    { value: "88", label: "88 - Pharmacy" },
    { value: "90", label: "90 - Mail Order Pharmacy" },
    { value: "96", label: "96 - Professional (Physician) Visit - Inpatient" },
    { value: "97", label: "97 - Anesthesiologist" },
    { value: "98", label: "98 - Professional (Physician) Visit - Office" },
    { value: "99", label: "99 - Otological / Audiological Services" },
    { value: "A0", label: "A0 - Burn Care" },
    { value: "A1", label: "A1 - Coronary Care" },
    { value: "A3", label: "A3 - Professional (Physician) Visit - Home" },
    { value: "A4", label: "A4 - Psychiatric" },
    { value: "A5", label: "A5 - Rehabilitation - Outpatient" },
    { value: "A6", label: "A6 - Psychotherapy" },
    { value: "A7", label: "A7 - Psychiatric - Inpatient" },
    { value: "A8", label: "A8 - Psychiatric - Outpatient" },
    { value: "A9", label: "A9 - Rehabilitation - Inpatient" },
    { value: "AB", label: "AB - Prosthetic Device" },
    { value: "AD", label: "AD - Occupational Therapy" },
    { value: "AE", label: "AE - Physical Medicine" },
    { value: "AF", label: "AF - Speech Therapy" },
    { value: "AG", label: "AG - Skilled Nursing Care" },
    { value: "AI", label: "AI - Substance Abuse" },
    { value: "AJ", label: "AJ - Alcoholism" },
    { value: "AK", label: "AK - Drug Addiction" },
    { value: "AL", label: "AL - Vision (Optometry)" },
    { value: "AM", label: "AM - Hearing" },
    { value: "AN", label: "AN - Gynecological" },
    { value: "AO", label: "AO - Dental Crowns" },
    { value: "BB", label: "BB - Partial Hospitalization (Psychiatric)" },
    { value: "BD", label: "BD - Cognitive Therapy" },
    { value: "BF", label: "BF - Pulmonary Rehabilitation" },
    { value: "BG", label: "BG - Cardiac Rehabilitation" },
    { value: "BH", label: "BH - Pediatric" },
    { value: "BK", label: "BK - Orthodontics" },
    { value: "BL", label: "BL - Dental Implants" },
    { value: "BN", label: "BN - Acupuncture" },
    { value: "BQ", label: "BQ - Bereavement Counseling" },
    { value: "BR", label: "BR - Brand Name Prescription Drug" },
    { value: "BZ", label: "BZ - Generic Prescription Drug / Wellness" },
    { value: "CE", label: "CE - Mental Health Facility - Inpatient" },
    { value: "CF", label: "CF - Mental Health Facility - Outpatient" },
    { value: "CG", label: "CG - Mental Health Provider - Inpatient" },
    { value: "CH", label: "CH - Mental Health Provider - Outpatient" },
    { value: "CI", label: "CI - Substance Abuse Facility - Inpatient" },
    { value: "CJ", label: "CJ - Substance Abuse Facility - Outpatient" },
    { value: "MH", label: "MH - Mental Health" },
    { value: "RT", label: "RT - Routine Exam" },
    { value: "UC", label: "UC - Urgent Care" },
]
